-- Do not edit.  Generated by cheby 1.5.dev0 using these options:
--  -i evt_cnt_regs.cheby --hdl vhdl --gen-hdl wb_evt_cnt_regs.vhd --doc html --gen-doc doc/wb_evt_cnt_regs_wb.html --gen-c wb_evt_cnt_regs.h --consts-style verilog --gen-consts ../../../../sim/regs/wb_evt_cnt_regs.vh --consts-style vhdl-ohwr --gen-consts ../../../../sim/regs/wb_evt_cnt_reg_consts.vhd
-- Generated on Mon Jul 25 07:59:38 2022 by augusto


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;

entity wb_evt_cnt_regs is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_i                 : in    t_wishbone_slave_in;
    wb_o                 : out   t_wishbone_slave_out;

    -- Event counter control register
    -- 0: Clear counter;
    -- 1: Copy counter value to cnt_snap.
    ctl_trig_act_o       : out   std_logic;

    -- A frozen snapshot of the internal counter.
    cnt_snap_i           : in    std_logic_vector(31 downto 0)
  );
end wb_evt_cnt_regs;

architecture syn of wb_evt_cnt_regs is
  signal adr_int                        : std_logic_vector(2 downto 2);
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal ctl_trig_act_reg               : std_logic;
  signal ctl_wreq                       : std_logic;
  signal ctl_wack                       : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(2 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  adr_int <= wb_i.adr(2 downto 2);
  wb_en <= wb_i.cyc and wb_i.stb;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_i.we)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_i.we) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_i.we)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_i.we) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_o.ack <= ack_int;
  wb_o.stall <= not ack_int and wb_en;
  wb_o.rty <= '0';
  wb_o.err <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wr_req_d0 <= '0';
      else
        rd_ack_int <= rd_ack_d0;
        wb_o.dat <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= adr_int;
        wr_dat_d0 <= wb_i.dat;
      end if;
    end if;
  end process;

  -- Register ctl
  ctl_trig_act_o <= ctl_trig_act_reg;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        ctl_trig_act_reg <= '0';
        ctl_wack <= '0';
      else
        if ctl_wreq = '1' then
          ctl_trig_act_reg <= wr_dat_d0(0);
        end if;
        ctl_wack <= ctl_wreq;
      end if;
    end if;
  end process;

  -- Register cnt_snap

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, ctl_wack) begin
    ctl_wreq <= '0';
    case wr_adr_d0(2 downto 2) is
    when "0" =>
      -- Reg ctl
      ctl_wreq <= wr_req_d0;
      wr_ack_int <= ctl_wack;
    when "1" =>
      -- Reg cnt_snap
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (adr_int, rd_req_int, ctl_trig_act_reg, cnt_snap_i) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case adr_int(2 downto 2) is
    when "0" =>
      -- Reg ctl
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= ctl_trig_act_reg;
      rd_dat_d0(31 downto 1) <= (others => '0');
    when "1" =>
      -- Reg cnt_snap
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0 <= cnt_snap_i;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
