-- Do not edit.  Generated by cheby 1.6.0rc1 using these options:
--  -i wb_si57x_ctrl_regs.cheby --hdl vhdl --gen-hdl wb_si57x_ctrl_regs.vhd --doc html --gen-doc doc/wb_si57x_ctrl_regs.html --gen-c wb_si57x_ctrl_regs.h --consts-style verilog --gen-consts ../../../../sim/regs/wb_si57x_ctrl_regs.vh --consts-style vhdl-ohwr --gen-consts ../../../../sim/regs/wb_si57x_ctrl_reg_consts.vhd
-- Generated on Thu Jun 13 17:05:03 2024 by augusto

library ieee;
use ieee.std_logic_1164.all;

package wb_si57x_ctrl_regs_consts_pkg is
  constant c_WB_SI57X_CTRL_REGS_SIZE : Natural := 24;
  constant c_WB_SI57X_CTRL_REGS_CTL_ADDR : Natural := 16#0#;
  constant c_ADDR_WB_SI57X_CTRL_REGS_CTL_READ_STRP_REGS : Natural := 16#0#;
  constant c_WB_SI57X_CTRL_REGS_CTL_READ_STRP_REGS_OFFSET : Natural := 0;
  constant c_ADDR_WB_SI57X_CTRL_REGS_CTL_APPLY_CFG : Natural := 16#0#;
  constant c_WB_SI57X_CTRL_REGS_CTL_APPLY_CFG_OFFSET : Natural := 1;
  constant c_WB_SI57X_CTRL_REGS_STA_ADDR : Natural := 16#4#;
  constant c_ADDR_WB_SI57X_CTRL_REGS_STA_STRP_COMPLETE : Natural := 16#4#;
  constant c_WB_SI57X_CTRL_REGS_STA_STRP_COMPLETE_OFFSET : Natural := 0;
  constant c_ADDR_WB_SI57X_CTRL_REGS_STA_CFG_IN_SYNC : Natural := 16#4#;
  constant c_WB_SI57X_CTRL_REGS_STA_CFG_IN_SYNC_OFFSET : Natural := 1;
  constant c_ADDR_WB_SI57X_CTRL_REGS_STA_I2C_ERR : Natural := 16#4#;
  constant c_WB_SI57X_CTRL_REGS_STA_I2C_ERR_OFFSET : Natural := 2;
  constant c_ADDR_WB_SI57X_CTRL_REGS_STA_BUSY : Natural := 16#4#;
  constant c_WB_SI57X_CTRL_REGS_STA_BUSY_OFFSET : Natural := 3;
  constant c_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_STRP_ADDR : Natural := 16#8#;
  constant c_ADDR_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_STRP_RFREQ_MSB_STRP : Natural := 16#8#;
  constant c_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_STRP_RFREQ_MSB_STRP_OFFSET : Natural := 0;
  constant c_ADDR_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_STRP_N1_STRP : Natural := 16#8#;
  constant c_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_STRP_N1_STRP_OFFSET : Natural := 6;
  constant c_ADDR_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_STRP_HSDIV_STRP : Natural := 16#8#;
  constant c_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_STRP_HSDIV_STRP_OFFSET : Natural := 13;
  constant c_WB_SI57X_CTRL_REGS_RFREQ_LSB_STRP_ADDR : Natural := 16#c#;
  constant c_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_ADDR : Natural := 16#10#;
  constant c_ADDR_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_RFREQ_MSB : Natural := 16#10#;
  constant c_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_RFREQ_MSB_OFFSET : Natural := 0;
  constant c_ADDR_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_N1 : Natural := 16#10#;
  constant c_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_N1_OFFSET : Natural := 6;
  constant c_ADDR_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_HSDIV : Natural := 16#10#;
  constant c_WB_SI57X_CTRL_REGS_HSDIV_N1_RFREQ_MSB_HSDIV_OFFSET : Natural := 13;
  constant c_WB_SI57X_CTRL_REGS_RFREQ_LSB_ADDR : Natural := 16#14#;
end package wb_si57x_ctrl_regs_consts_pkg;
