onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /trigger_io_tb/c_rx_counter_width
add wave -noupdate /trigger_io_tb/c_rx_debounce_width
add wave -noupdate /trigger_io_tb/c_rx_delay_width
add wave -noupdate /trigger_io_tb/c_tx_counter_width
add wave -noupdate /trigger_io_tb/c_tx_delay_width
add wave -noupdate /trigger_io_tb/c_tx_extensor_width
add wave -noupdate /trigger_io_tb/clk
add wave -noupdate /trigger_io_tb/pulse_from_fpga
add wave -noupdate /trigger_io_tb/pulse_from_pad
add wave -noupdate /trigger_io_tb/rst_n
add wave -noupdate /trigger_io_tb/test_begin_pulse
add wave -noupdate /trigger_io_tb/test_end
add wave -noupdate /trigger_io_tb/trig_dbg
add wave -noupdate /trigger_io_tb/trig_dir
add wave -noupdate /trigger_io_tb/trig_ext_dir_pol
add wave -noupdate /trigger_io_tb/trig_in
add wave -noupdate /trigger_io_tb/trig_out
add wave -noupdate /trigger_io_tb/trig_pad_dir
add wave -noupdate /trigger_io_tb/trig_pad_in
add wave -noupdate /trigger_io_tb/trig_pad_inout
add wave -noupdate /trigger_io_tb/trig_pad_out
add wave -noupdate /trigger_io_tb/trig_rx_cnt
add wave -noupdate /trigger_io_tb/trig_rx_debounce_length
add wave -noupdate /trigger_io_tb/trig_rx_delay_length
add wave -noupdate /trigger_io_tb/trig_rx_rst_n
add wave -noupdate /trigger_io_tb/trig_tx_cnt
add wave -noupdate /trigger_io_tb/trig_tx_delay_length
add wave -noupdate /trigger_io_tb/trig_tx_extensor_length
add wave -noupdate /trigger_io_tb/trig_tx_rst_n
add wave -noupdate -divider DUT
add wave -noupdate /trigger_io_tb/DUT/clk_i
add wave -noupdate /trigger_io_tb/DUT/g_iobuf_instantiation_type
add wave -noupdate /trigger_io_tb/DUT/g_rx_counter_width
add wave -noupdate /trigger_io_tb/DUT/g_rx_debounce_width
add wave -noupdate /trigger_io_tb/DUT/g_rx_delay_width
add wave -noupdate /trigger_io_tb/DUT/g_sync_edge
add wave -noupdate /trigger_io_tb/DUT/g_tx_counter_width
add wave -noupdate /trigger_io_tb/DUT/g_tx_delay_width
add wave -noupdate /trigger_io_tb/DUT/g_tx_extensor_width
add wave -noupdate /trigger_io_tb/DUT/g_with_bidirectional_trigger
add wave -noupdate /trigger_io_tb/DUT/rst_n_i
add wave -noupdate /trigger_io_tb/DUT/trig_dir_i
add wave -noupdate /trigger_io_tb/DUT/trig_ext_dir_pol_i
add wave -noupdate /trigger_io_tb/DUT/trig_i
add wave -noupdate /trigger_io_tb/DUT/trig_in_i
add wave -noupdate /trigger_io_tb/DUT/trig_rx_debounce_length_i
add wave -noupdate /trigger_io_tb/DUT/trig_rx_delay_length_i
add wave -noupdate /trigger_io_tb/DUT/trig_rx_rst_n_i
add wave -noupdate /trigger_io_tb/DUT/trig_tx_delay_length_i
add wave -noupdate /trigger_io_tb/DUT/trig_tx_extensor_length_i
add wave -noupdate /trigger_io_tb/DUT/trig_tx_rst_n_i
add wave -noupdate /trigger_io_tb/DUT/trig_dbg_o
add wave -noupdate /trigger_io_tb/DUT/trig_dir_o
add wave -noupdate /trigger_io_tb/DUT/trig_o
add wave -noupdate /trigger_io_tb/DUT/trig_out_o
add wave -noupdate /trigger_io_tb/DUT/trig_rx_cnt_o
add wave -noupdate /trigger_io_tb/DUT/trig_tx_cnt_o
add wave -noupdate /trigger_io_tb/DUT/trig_b
add wave -noupdate /trigger_io_tb/DUT/trig_in_phys
add wave -noupdate /trigger_io_tb/DUT/trig_out_phys
add wave -noupdate -divider physical
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/g_with_bidirectional_trigger
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/g_iobuf_instantiation_type
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/clk_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/rst_n_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_dir_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_ext_dir_pol_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_in_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_b
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_rx
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_rx_fpga
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_tx
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_tx_fpga
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_tx_int
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_dir
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_dir_int
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_pol_int
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_dir_polarized
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_tx_polarized
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_dir_ext
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/c_trig_dir_fpga_input
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/c_trig_dir_fpga_output
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_dir_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_physical/trig_out_o
add wave -noupdate -divider rx
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/g_sync_edge
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/g_rx_debounce_width
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/g_rx_counter_width
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/g_rx_delay_width
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/clk_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/rst_n_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_rx_debounce_length_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_rx_delay_length_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_rx_rst_n_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_rx
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_rx_debounced
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_rx_debounced_dly
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_rx_cnt_slv
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_rx_cnt_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/trig_out_o
add wave -noupdate -divider input_sync
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/clk_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/data_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/g_sync_edge
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/npulse_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/ppulse_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/rst_n_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/sync0
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/sync1
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/sync2
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_input_sync/synced_o
add wave -noupdate -divider debounce
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_deglitcher/clk_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_deglitcher/dat_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_deglitcher/dat_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_deglitcher/filt_cnt
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_deglitcher/g_len_width
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_deglitcher/len_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_rx_datapath/cmp_trigger_rx/cmp_deglitcher/rst_n_i
add wave -noupdate -divider tx
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/g_tx_extensor_width
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/g_tx_counter_width
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/g_tx_delay_width
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/clk_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/rst_n_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_tx_extensor_length_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_tx_delay_length_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_tx_rst_n_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_in_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_tx
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_tx_dly
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_tx_dly_extended
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_tx_cnt_slv
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_tx_cnt_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/trig_o
add wave -noupdate -divider delay
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/clk_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/delay_cnt
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/delay_cnt_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/delay_cnt_max
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/delay_fsm_current_state
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/g_delay_cnt_width
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/pulse
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/pulse_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/pulse_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/rdy
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/rdy_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_delay_gen_dyn/rst_n_i
add wave -noupdate -divider extend
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_extend_pulse/clk_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_extend_pulse/cntr
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_extend_pulse/extended_int
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_extend_pulse/extended_o
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_extend_pulse/g_width_bus_size
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_extend_pulse/pulse_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_extend_pulse/pulse_width_i
add wave -noupdate /trigger_io_tb/DUT/cmp_trigger_io_tx_datapath/cmp_tx_extend_pulse/rst_n_i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1940000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {897929 ps} {2528247 ps}
